### ISSUE TITLE
Module Updates - Piping

### ISSUE THREAD

**Issue by moorejr5** [smartinkc/Multilingual#1]
Hello,

This is Ryan Moore from Vanderbilt. I work with Adam Lewis, who has contacted you already on the REDCap Consortium website regarding a client we have requesting data piping in the translations. I'm reaching out in terms of my thoughts on it and to start a dialog about implementing updates.

As far as trying to make the update as simple as possible, I think the REDCap class 'Piping' is the way to go, using the function 'replaceVariablesInLabel'. I think it should allow for piping without too much need for changes to the module itself.

Regarding the actual work in getting updates done, I will have to submit to whatever you feel comfortable with. This module has your name on it, so I didn't want to go tinkering with it out of the blue. However, since its one of our clients requesting updates, I also didn't want to place the burden on you, either. Everyone has their own responsibilities, so I don't know what kind of bandwidth you'd have for this request. I'd be comfortable with going about this in whatever manner you are, just let me know.

**Comment by smartinkc** [comment]
Hi Ryan, thank you for the suggestion. I was thinking this would need to
take place in the javascript and had no idea that we had access to an
existing function.  Makes more sense to use the REDCap function.

I'm good either way if you want add it or tell me what to add.

I may have some time tomorrow or Friday to try it out if you don't get to
it.

Steve

**Comment by moorejr5** [comment]
Just as a follow up on this:

I haven't heard back on a timeline from the client on a 'need this done' deadline for this stuff. If you're able to work on it any time reasonably soon I think that would be alright. If something else comes up and you're unable just let me know.

**Comment by smartinkc** [comment]
So somewhere between versions 7 and 8, the questions on the survey were moved to a label element.  Right now I am hiding that element.  I need to update the javascript to replace the html within those tags as opposed to hiding them.  Then maybe we can use the piping.

**Comment by alewis64** [comment]
@smartinkc or @moorejr5  has there been any progress on getting the Piping to work?

**Comment by smartinkc** [comment]
@alewis64 I'm sorry, I have not had the time to look further into this.  See my previous post.  I need to take some time a do a bit of an overhaul since we originally wrote it for version 7.x and are now on 8.x.  It's on my radar though.

**Comment by smartinkc** [comment]
@alewis64 
@moorejr5 
I added piping to the data entry and survey pages.  I haven't created a new version yet, because I figured maybe you could take a look and maybe test to see if it's working for you.  Ryan, thanks for the suggestion to use the Piping class, that is what I did.  Right now it only passes the label, record and event_id (line 117 of the multilingual.php file).  Please take a look and if you think it's working I'll submit a new version.

**Comment by smartinkc** [comment]
This has been added. v1.7
