### ISSUE TITLE
Consider changing "languages" variable to ml_languages

### ISSUE THREAD

**Issue by biggeeves** [smartinkc/Multilingual#10]
Using the variable "languages" is great for new projects.  When older projects decide to become multilingual it can be problematic if "languages" is already a variable on an existing REDCAp instrument.  

Using the variable name "ml_languages" would almost guarantee that the variable name is unique in the project.  As all variable names in REDCAp must be unique this would be one possible solution.

Another solution is to allow the user to define the variable name in "Project Settings" configuration.  This would be the more robust solution however a bit more to code. 

GN

**Comment by smartinkc** [comment]
This is a good idea.  We've run into this ourselves.  I will make it a setting in the next release.  Thanks for the idea.

Steve

**Comment by smartinkc** [comment]
added to config

**Comment by biggeeves** [comment]
Thank you!
