### ISSUE TITLE
Messages for "required" fields are missing

### ISSUE THREAD

**Issue by gadeynebram** [smartinkc/Multilingual#12]
Hi,

I'm using the latest Multilingual 1.8.5.

One of our users mentioned that the labels for required fields are missing. Is it possible that these are removed by the plugin? I see them very briefly on the page and then they disappear (presumably when the JavaScript is fully executed). 

This is a screenshot of the configurator. I've added "Required Field" in all the error/validation messages fields but the result is the same with or without them: 

![image](https://user-images.githubusercontent.com/3693399/45296682-1ebc8200-b503-11e8-8aba-874d53fd97a8.png)

This is a screenshot of the translated survey:

![image](https://user-images.githubusercontent.com/3693399/45296381-2891b580-b502-11e8-94c2-c2ecb9dadba0.png)

And this happens after clicking on the "V" button:

![image](https://user-images.githubusercontent.com/3693399/45296434-49f2a180-b502-11e8-8c06-7122b6ad4b31.png)

In the survey settings I have the option "For 'Required' fields, display the red 'must provide value' text on the survey page?" set to "Yes".

**Comment by smartinkc** [comment]
Yes, this is on purpose because it is hard-coded English.  The best way to handle them is to add them as a span in the translations:

<span class="multilingual">*must provide value</span>

**Comment by gadeynebram** [comment]
@smartinkc , if that's oké with you, I'd like to try and write some code that (similar to the languages field) extracts translations for "*must provide value".

**Comment by smartinkc** [comment]
Please do!

**Comment by gadeynebram** [comment]
@smartinkc, I've created pull request #13 with a proposal to provide a generic solution.
