### ISSUE TITLE
No response when user is not logged in

### ISSUE THREAD

**Issue by gadeynebram** [smartinkc/Multilingual#2]
Hi,

In survey mode, in the function getLanguages() there is an ajax call to https://redcap.location/redcap_v8.1.5/ExternalModules/?id=1&page=index&pid=15 with payload data=%7B%22todo%22%3A2%2C%22project_id%22%3A15%2C%22field_name%22%3A%22languages%22%7D.

In Google chrome I do get a response at this point. In Internet Explorer, a HTML page is returned that does not make much sense.

I'm still trying to debug this issue. It even seems like getData.php is never called.

**Comment by gadeynebram** [comment]
This is file contains the current response.

[response.zip](https://github.com/smartinkc/Multilingual/files/1740648/response.zip)

**Comment by smartinkc** [comment]
Bram, I just tested IE 11 and it is working for me.  The response that you added looks like REDCap login page.  Almost like it's not respecting the no-auth settings. Try to download the latest version, getData.php is no longer used (functions moved to the multilingual class).  The new file that it tries to call is the index.php page which is in the no-auth section of the config.json file (should not require loggin in).

**Comment by gadeynebram** [comment]
Hi,

We are on version 1.3. Indeed I think that this bug is related to setting the no-auth settting. If I'm logged in to redcap and I open a survey link in the same browser then everythink works fine. If I open the link in a separate browser where I'm not logged in to redcap (which was IE11) then I get this issue. I'll check this further.

**Comment by gadeynebram** [comment]
@smartinkc,

Do you have any further thoughts on this and on pull request #3?

**Comment by smartinkc** [comment]
The IE11 problem stumps me because it doesn't make sense.  Whether you make a request in Chrome, IE or any other browswer, the response from the server should be the same.  Do you think you can grab the network request and response from the developer tools in IE?

**Comment by smartinkc** [comment]
Hang on,  I am able to reproduce this now...

Is this the error you are getting: 
Object.keys: argument is not an Object

**Comment by smartinkc** [comment]
Bram, there is a new version, 1.6. Please see if that fixes the issue

Steve

**Comment by gadeynebram** [comment]
@smartinkc ,

Thanks for the update! In my test environment it seems to work fine now!
