### ISSUE TITLE
Red stop sign overlaying error messages in instrument?

### ISSUE THREAD

**Issue by npw1982** [smartinkc/Multilingual#21]
This may not be an issue, and is probably just my understanding of the module, but:

I have a test project with one instrument (using v1.8.9), and when applying translations to the error messages they seem to get overlayed with a stop sign (see below)...

The message does appear very briefly before being overlayed with the sign, this was using the Project Level Default messages.

Thanks!
Neil

![image](https://user-images.githubusercontent.com/47890938/53244089-b670ef80-36a1-11e9-8657-83822ab8e3ea.png)

**Comment by smartinkc** [comment]
Hi Neil, we have not added the default error messages to the data entry side yet. It's supposed to be a universal "stop, something is wrong" sign.  I'll make sure they get into the next version.  

Steve

**Comment by npw1982** [comment]
Ah great thanks! I think it was a misunderstanding on my part then, I've just enabled it as a Survey and the inline errors are displayed correctly, it's just the data entry instruments that show the red stop sign. But it sounds like that is the intended behaviour.
