### ISSUE TITLE
Not working for checkboxes

### ISSUE THREAD

**Issue by manuelsnyder** [smartinkc/Multilingual#22]
The Multilingual external module isn't translating the checkbox answers.

![multilingual display error](https://imgur.com/XKvpRTE.png)

Action Tags
```
@p1000lang{"עברית":"טיפול","عربيه":"علاج","English":"Treatment"}
@p1000answers{"עברית":{"1":"כימותרפיה","2":"רדיותרפיה","3":"ניתוח","4":"טיפול הורמונלי","5":"מעכבי ארומטאז","6":"טיפול אנדוקריני"},"عربيه":{"1":"العلاج الكيميائي","2":"المعالجة بالإشعاع","3":"تحليل","4":"العلاج الهرموني","5":"مثبطات الهرمونات","6":"علاج الغدد الصماء"},"English":{"1":"Chemotherapy","2":"Radiotherapy","3":"Surgery","4":"Hormonal Treatment","5":"Aromatase Inhibitor","6":"Endocrine Therapy"}}
```

![online designer view](https://imgur.com/yrKRP6V.png)

**Comment by smartinkc** [comment]
If you open the javascript console, are you getting any errors? We have struggled with Arabic fonts in the past. We've found that google translate produces a web safe font that does work.

**Comment by manuelsnyder** [comment]
Looks like that might be the issue.

In the javascript console, there are two errors, both say:
**Failed to load resource: the server responded with a status of 404 (Not Found)**

And the links for each are are: 
https://redcap.uahs.arizona.edu/redcap_v8.11.5/Resources/css/fontawesome/webfonts/fa-regular-400.woff2
https://redcap.uahs.arizona.edu/redcap_v8.11.5/Resources/css/fontawesome/webfonts/fa-solid-900.woff2

I copied/pasted the translations from Google Translate when I initially set up the form. Is there something else I need to do to utilize the web safe font from there?

**Comment by smartinkc** [comment]
I noticed you are on a newer version, so I updated my local REDCap.  My checkboxes are working.  The next step should be to clear out all translations for just that question and reenter them.

**Comment by manuelsnyder** [comment]
I cleared out the translations and entered them again, but they still don't change. I also created a new checkbox field and added the translations, and that didn't work either. Finally, I created a new checkbox field and added dummy answers in English to see if it was the Arabic font that was the problem, but even the English answers didn't change when I clicked through the languages.

**Comment by smartinkc** [comment]
I'm not sure what it is, but it's something to do with the font. The json code you posted above is backwards.  When I try to switch it, it switches back. What language is it?

**Comment by manuelsnyder** [comment]
The project that I'm working on is using three languages; Hebrew, Arabic, and English. I'm typing the English into Google Translate, copying from there and pasting it into the multilingual text boxes for each language. 

I'm also using the Right-to-Left external module, so that might be why the JSON is backwards. Everything is working for all of my other textbox and radio button fields. It just seems to be a problem with the checkboxes.

**Comment by smartinkc** [comment]
I just copied your English and put it into Google translate and it works.  Maybe turn off the other module.  Multilingual will change it to right to left if it detects Arabic

![image](https://user-images.githubusercontent.com/18448665/53978373-a52bd800-40d0-11e9-92f7-2a99708d25dd.png)

![image](https://user-images.githubusercontent.com/18448665/53978412-c4c30080-40d0-11e9-816d-42315aecd0b7.png)

**Comment by stockstarke** [comment]
is there a way to make Hebrew aligned from right to left as well (just like Arabic) using Multilingual? I cant seem to figure out how to do it.

**Comment by manuelsnyder** [comment]
One of the ways I found to display the text from right-to-left is to use the REDCap CSS Injector and use the direction property. Something like:

element {
   direction: rtl;
}

You can add the rule to the whole form or just an individual field, depending on how you write the CSS rule.
