### ISSUE TITLE
New answer options are not visible when in draft mode

### ISSUE THREAD

**Issue by gadeynebram** [smartinkc/Multilingual#25]
@smartinkc ,

We've noticed that additional added answer options do not result in new fields to enter translations, unless the additional new answer options are first committed.

**Comment by smartinkc** [comment]
@gadeynebram, thank you for finding this.  I will test as soon as I can and merge the code.

**Comment by gadeynebram** [comment]
@smartinkc ,

Any news on this?

**Comment by smartinkc** [comment]
@gadeynebram, do you want to test and make sure it's working as expected?

**Comment by gadeynebram** [comment]
@smartinkc ,

I like the system setting idea.

I've tested it and it works. The behaviour indeed corresponds to the system setting.
