### ISSUE TITLE
Survey login-page and save-and-return-later information not translatable

### ISSUE THREAD

**Issue by Gesine-TUD** [smartinkc/Multilingual#27]
Hi,

It seems there is currently no way to translate the survey login-message and the message a participant receives when filling out a survey and deciding to save and return later (see both screenshots below). Maybe I just have missed it - is there a way to translate both?

Best,
Gesine

![Survey Login](https://user-images.githubusercontent.com/54995296/64447061-c189eb00-d0da-11e9-8b16-45743151e583.png)
![Save-and-return-later](https://user-images.githubusercontent.com/54995296/64447069-c484db80-d0da-11e9-97bd-df2216d2b79b.png)

**Comment by smartinkc** [comment]
Unfortunately, we have not translated the login part yet, but the save and return later has been.  Look in the external module settings

![image](https://user-images.githubusercontent.com/18448665/64447666-8f0fcc00-d0a1-11e9-8499-efb5f4975318.png)

I will add the login part to the to-do list

Steve

**Comment by Gesine-TUD** [comment]
Hi Steve,

Thanks for your quick response! I use REDCap version 9.3.3 and the multilingual module; however, when saving translated text in the save-and-return-later option, it does not translate to the survey. The button on the survey page is correctly translated (save & return later), but the text that is shown when clicking on the save-&-return-later button (as shown in the second screenshot above) is still in English. 

Best, Gesine

**Comment by rhuebner1** [comment]
Hi @Gesine-TUD, 

Have you had any luck translating the save and return later text? I am having the same issue .

Thank you!
Rachael

**Comment by smartinkc** [comment]
New version coming out soon...
