### ISSUE TITLE
After importing a metadata XML from one redcap instance to another, the translations stop working

### ISSUE THREAD

**Issue by gadeynebram** [smartinkc/Multilingual#4]
For languages I have this in the languages field:

`1, fr | 2, nl | 3, pt | 4, cs | 5, en`

This translates to xml as 

```xml
<CodeList OID="languages.choices" Name="languages" DataType="text" redcap:Variable="languages">
	<CodeListItem CodedValue="1"><Decode><TranslatedText>fr</TranslatedText></Decode></CodeListItem>
	<CodeListItem CodedValue="2"><Decode><TranslatedText>nl</TranslatedText></Decode></CodeListItem>
	<CodeListItem CodedValue="3"><Decode><TranslatedText>pt</TranslatedText></Decode></CodeListItem>
	<CodeListItem CodedValue="4"><Decode><TranslatedText>cs</TranslatedText></Decode></CodeListItem>
	<CodeListItem CodedValue="5"><Decode><TranslatedText>en</TranslatedText></Decode></CodeListItem>
</CodeList>
```
If you download the dictionary after importing the metadata file you get:

`1, fr|2, nl|3, pt|4, cs|5, en`

As you can see the spaces before and after the | are removed.

In the MySQL database I see that after import the element_enum field contains `1, fr\n2, nl\n3, pt\n4, cs`. For re-uploaded dictionaries this field contains `1, fr \n 2, nl \n 3, pt \n 4, cs \n 5, en`.

The result for the call to get the translations is `{"1":"fr\\n2"}` where `{"1":"fr","2":"nl","3":"pt","4":"cs"}` is expected

**Comment by smartinkc** [comment]
This should be fixed.  Look for v1.7
