### ISSUE TITLE
Multilingual buttons not working outside of Chrome

### ISSUE THREAD

**Issue by willsvankumc** [smartinkc/Multilingual#45]
Running redcap_v9.5.25, our multilingual module only displays buttons on chrome. On other browsers it goes straight to the english button without selection, and buttons also don't display in private browsing window (firefox, edge). Tested on firefox, IE, Safari, and explorer. our multilingual module version v1.9.8.

**Comment by willsvankumc** [comment]
I have resolved this with stephen martin in the redcap community. It was an httpd permissions error on my end.

**Comment by anbritt** [comment]
I am having the same issue with the buttons not appearing in Chrome and Safari - Could you provide more detail on how you resolved this issue?
