### ISSUE TITLE
Unable to use negative values as coded value in multiple choice fields

### ISSUE THREAD

**Issue by steentje34** [smartinkc/Multilingual#6]
Due to the way the functions updateActionTags() & updateActionTagsMatrix() are programmed, it is currently not possible to use negative coded values in multiple choice fields using the multilingual EM. The user can add a translation for negative coded values, but it is not saved correctly in the action tag. For example, for a question "How do you feel?", the answer choices are Good (coded value: 1), Neutral (coded value: 0) & Bas (coded value: -1). This results in following action tag:
`@p1000answers{"English":{"0":"Neutral","1":"Good","":"Bad"},"Nederlands":{"0":"Neutraal","1":"Goed","":"Slecht"}}`

It seems to be linked to (at least) following lines of code:
https://github.com/smartinkc/Multilingual/blob/b1d13b4ffc1cfdaf19d7bb0deab8a482129996e9/js/multilingual_setup.js#L293
https://github.com/smartinkc/Multilingual/blob/b1d13b4ffc1cfdaf19d7bb0deab8a482129996e9/js/multilingual_setup.js#L343

Would it be possible to fix this bug?
Thanks!
Simon

**Comment by smartinkc** [comment]
Simon, can you validate for me that replacing the above line (in both functions) with these 2 lines:

tmp = tmp.replace('-',':');
tmp = tmp.split(':');

fixes your issue?

Thanks,

Steve

**Comment by steentje34** [comment]
This seems to fix the issue. Thanks!

**Comment by smartinkc** [comment]
I will push a new version here with the fix.  Thanks for finding!
