### ISSUE TITLE
Add a reminder on language codings

### ISSUE THREAD

**Issue by nbchan** [smartinkc/Multilingual#7]
I'm currently using the multilingual external module and I started with the following choices in the variable "languages":
> en, English
> ch, 中文
> fr, Francais

I immediately ran into error when viewing the survey page, saying that the length property of `lang` cannot be accessed in this line as `lang` is `undefined`. 
https://github.com/smartinkc/Multilingual/blob/21002329a3e3c08689c54f9897f1bd5d34651e45/js/multilingual_survey.js#L253

Subsequent checking revealed that this (*) is the line causing the assignment of undefined to lang. 
https://github.com/smartinkc/Multilingual/blob/21002329a3e3c08689c54f9897f1bd5d34651e45/js/multilingual_survey.js#L432 
In this case, `languages` takes on these values: `{en: "English", ch: "中文", fr, "Francais"}`

A partial fix to this issue is to change the line (*) to 
`lang = languages[Object.keys(languages)[0]];`
Then the page would be able to default to the language en. However, the `#changeLang` button still failed to function properly. I did not go on and investigate but I believe this is fixable.

Therefore, it is suggested to add a minor note to the documentation saying that the default language has to be encoded with 1, or extend it so that string encodings can be supported.

Thanks for all your work!

**Comment by smartinkc** [comment]
I have added your suggestion to both the readme and the popup in the online designer.  Thanks!
