### ISSUE TITLE
In case of a descriptive field the content is appended instead of added

### ISSUE THREAD

**Issue by gadeynebram** [smartinkc/Multilingual#8]
Hi,

I have a descriptive field that contains some html code as the field label. The translations also contain the same structure.

```html
<span style='font-weight: normal;'>
    <p>some other html<p>
    <ul>
        <li>with lists</li>
    </ul>
</span>
```
This code appends the label for the selected language instead of replacing it.

https://github.com/smartinkc/Multilingual/blob/21002329a3e3c08689c54f9897f1bd5d34651e45/js/multilingual_survey.js#L277-L283

**Comment by smartinkc** [comment]
Add class="multilingual" to the outer most html element.  That will remove it.

**Comment by gadeynebram** [comment]
Thanks, that works indeed!
